version: 2.1

jobs:
  build:
    working_directory: ~/.CI-Golang
    docker:
      - image: "circleci/golang:1.15.13"
    steps:
      - add_ssh_keys:
            fingerprints:
              - "88:c3:55:3e:99:06:a8:58:13:d4:af:2f:16:28:8f:92"
      - checkout
      - run: echo "===安装需求环境=="
      - run: go mod tidy
      - run: echo "===开始部署==="
      - run: go build
      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              rsync -avce ssh build $SSH_USER@$SSH_IP:/data/corki-ui-web/
            else
              echo "Not master branch, dry run only"
            fi
      - run: echo "===部署完毕==="
workflows:
  version: 2
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build

#workflows:
#  build:
#    jobs:
#      - build